-- ============================================================
-- SCRIPT DDL: 6 Tabelas com Chaves Estrangeiras Simples (Seguro)
-- Arquivo: ddl_tabelas_fk_simples.sql
-- Sistema: Infratec - Segurança no Trabalho (PostgreSQL/Supabase)
-- ============================================================

-- 1. TABELAS DE DOMÍNIO (Sem Chave Estrangeira)

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_sistema VARCHAR(100) NOT NULL DEFAULT 'Infratec - Segurança no Trabalho',
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS epi (
    id_epi INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epi_nome VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS tipo_inspecao (
    id_tipo_inspecao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(100) NOT NULL
);

-- 2. TABELAS DEPENDENTES (Com Chave Estrangeira Simples)

CREATE TABLE IF NOT EXISTS funcionario (
    matricula INT PRIMARY KEY,
    nome_funcionario VARCHAR(100) NOT NULL,
    setor VARCHAR(50) NOT NULL,
    cargo VARCHAR(50) NOT NULL,
    id_usuario INT,
    CONSTRAINT fk_funcionario_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuario(id_usuario)
        ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS inspecao (
    id_inspecao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_inspecao INT NOT NULL,
    matricula_responsavel INT NOT NULL,
    data_inspecao TIMESTAMP NOT NULL,
    resultado_inspecao VARCHAR(255) NOT NULL,
    CONSTRAINT fk_inspecao_tipo
        FOREIGN KEY (id_tipo_inspecao)
        REFERENCES tipo_inspecao(id_tipo_inspecao)
        ON DELETE CASCADE,
    CONSTRAINT fk_inspecao_responsavel
        FOREIGN KEY (matricula_responsavel)
        REFERENCES funcionario(matricula)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS ocorrencia (
    id_ocorrencia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula INT NOT NULL,
    id_inspecao INT,
    tipo_ocorrencias VARCHAR(50) NOT NULL,
    gravidade VARCHAR(10) NOT NULL,
    data_ocorrencia DATE NOT NULL,
    CONSTRAINT fk_ocorrencia_funcionario
        FOREIGN KEY (matricula)
        REFERENCES funcionario(matricula)
        ON DELETE CASCADE,
    CONSTRAINT fk_ocorrencia_inspecao
        FOREIGN KEY (id_inspecao)
        REFERENCES inspecao(id_inspecao)
        ON DELETE SET NULL,
    CONSTRAINT chk_gravidade
        CHECK (gravidade IN ('Leve', 'Média', 'Grave'))
);
