-- ============================================================
-- ARQUIVO: ddl_tabelas_FK_composta.sql
-- SCRIPT DDL: Tabelas com Chaves Estrangeiras (FKs)
-- Alinhado estritamente com o Dicionário de Dados do Sistema
-- Sistema: Infratec - Segurança no Trabalho (PostgreSQL/Supabase)
-- ============================================================

-- 1. LIMPEZA AUTOMÁTICA
DROP TABLE IF EXISTS funcionario_epi, epi, treinamento CASCADE;

-- 2. TABELA: epi (Equipamentos de segurança - Vinculada ao Funcionário)
CREATE TABLE epi (
    id_epi INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula INT NOT NULL,
    epi_nome VARCHAR(100) NOT NULL,
    data_entrega_epi DATE NOT NULL,
    validade_epi DATE NOT NULL,
    status_epi VARCHAR(20) NOT NULL,
    CONSTRAINT fk_epi_funcionario
        FOREIGN KEY (matricula)
        REFERENCES funcionario(matricula)
        ON DELETE CASCADE,
    CONSTRAINT chk_status_epi
        CHECK (status_epi IN ('Ativo', 'Vencido', 'Substituído'))
);

-- 3. TABELA: treinamento (Treinamentos do Colaborador)
CREATE TABLE treinamento (
    id_treinamentos INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula INT NOT NULL,
    data_treinamento DATE NOT NULL,
    situacao_treinamento VARCHAR(20) NOT NULL,
    aviso_treinamento VARCHAR(150),
    CONSTRAINT fk_treinamento_funcionario
        FOREIGN KEY (matricula)
        REFERENCES funcionario(matricula)
        ON DELETE CASCADE,
    CONSTRAINT chk_situacao_treino
        CHECK (situacao_treinamento IN ('Concluído', 'Pendente', 'Cancelado'))
);
