DROP TABLE IF EXISTS funcionario_epi, treinamento, ocorrencia, inspecao, funcionario, tipo_inspecao, epi, usuario CASCADE;
-- ============================================================
-- SCRIPT DDL COMPLETO (SISTEMA INFRATEC)
-- ============================================================

CREATE TABLE usuario (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_sistema VARCHAR(100) NOT NULL DEFAULT 'Infratec - Segurança no Trabalho',
    email VARCHAR(150) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL
);

CREATE TABLE epi (
    id_epi INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    epi_nome VARCHAR(100) NOT NULL
);

CREATE TABLE tipo_inspecao (
    id_tipo_inspecao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descricao VARCHAR(100) NOT NULL
);

CREATE TABLE funcionario (
    matricula INT PRIMARY KEY,
    nome_funcionario VARCHAR(100) NOT NULL,
    setor VARCHAR(50) NOT NULL,
    cargo VARCHAR(50) NOT NULL,
    id_usuario INT,
    CONSTRAINT fk_funcionario_usuario 
        FOREIGN KEY (id_usuario) 
        REFERENCES usuario(id_usuario) 
        ON DELETE SET NULL
);

CREATE TABLE inspecao (
    id_inspecao INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_tipo_inspecao INT NOT NULL,
    matricula_responsavel INT NOT NULL,
    data_inspecao TIMESTAMP NOT NULL,
    resultado_inspecao VARCHAR(255) NOT NULL,
    CONSTRAINT fk_inspecao_tipo 
        FOREIGN KEY (id_tipo_inspecao) 
        REFERENCES tipo_inspecao(id_tipo_inspecao) 
        ON DELETE CASCADE,
    CONSTRAINT fk_inspecao_responsavel 
        FOREIGN KEY (matricula_responsavel) 
        REFERENCES funcionario(matricula) 
        ON DELETE CASCADE
);

CREATE TABLE ocorrencia (
    id_ocorrencia INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula INT NOT NULL,
    id_inspecao INT,
    tipo_ocorrencias VARCHAR(50) NOT NULL,
    gravidade VARCHAR(10) NOT NULL,
    data_ocorrencia DATE NOT NULL,
    CONSTRAINT fk_ocorrencia_funcionario 
        FOREIGN KEY (matricula) 
        REFERENCES funcionario(matricula) 
        ON DELETE CASCADE,
    CONSTRAINT fk_ocorrencia_inspecao 
        FOREIGN KEY (id_inspecao) 
        REFERENCES inspecao(id_inspecao) 
        ON DELETE SET NULL,
    CONSTRAINT chk_gravidade 
        CHECK (gravidade IN ('Leve', 'Média', 'Grave'))
);

CREATE TABLE funcionario_epi (
    id_funcionario_epi INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula INT NOT NULL,
    id_epi INT NOT NULL,
    data_entrega_epi DATE NOT NULL,
    validade_epi DATE NOT NULL,
    status_epi VARCHAR(20) NOT NULL,
    CONSTRAINT fk_funcepi_funcionario
        FOREIGN KEY (matricula)
        REFERENCES funcionario(matricula)
        ON DELETE CASCADE,
    CONSTRAINT fk_funcepi_epi
        FOREIGN KEY (id_epi)
        REFERENCES epi(id_epi)
        ON DELETE CASCADE,
    CONSTRAINT chk_status_epi
        CHECK (status_epi IN ('Ativo', 'Vencido', 'Substituído'))
);

CREATE TABLE treinamento (
    id_treinamentos INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    matricula INT NOT NULL,
    data_treinamento DATE NOT NULL,
    situacao_treinamento VARCHAR(20) NOT NULL,
    aviso_treinamento VARCHAR(150),
    CONSTRAINT fk_treinamento_funcionario
        FOREIGN KEY (matricula)
        REFERENCES funcionario(matricula)
        ON DELETE CASCADE,
    CONSTRAINT chk_situacao_treino
        CHECK (situacao_treinamento IN ('Concluído', 'Pendente', 'Cancelado'))
);
