-- ============================================================
-- ARQUIVO: ddl_tabelas_FK_composta.sql
-- SCRIPT DDL: Tabelas Associativas e Relacionamentos N:M
-- Sistema: Infratec - Segurança no Trabalho (PostgreSQL/Supabase)
-- ============================================================
-- PRÉ-REQUISITOS:
-- As tabelas 'funcionario' e 'epi' devem existir no banco.

-- 1. TABELA ASSOCIATIVA: Histórico de Entregas de EPIs
-- Modela a relação N:M entre Funcionário e EPI
CREATE TABLE funcionario_epi (
id_funcionario_epi INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
matricula INT NOT NULL,
id_epi INT NOT NULL,
data_entrega_epi DATE NOT NULL,
validade_epi DATE NOT NULL,
status_epi VARCHAR(20) NOT NULL,
CONSTRAINT fk_funcepi_funcionario
FOREIGN KEY (matricula)
REFERENCES funcionario(matricula)
ON DELETE CASCADE,
CONSTRAINT fk_funcepi_epi
FOREIGN KEY (id_epi)
REFERENCES epi(id_epi)
ON DELETE CASCADE,
CONSTRAINT chk_status_epi
CHECK (status_epi IN ('Ativo', 'Vencido', 'Substituído'))
);

-- 2. TABELA ASSOCIATIVA: Histórico de Treinamentos
-- Modela a relação ligada diretamente ao Funcionário
CREATE TABLE treinamento (
id_treinamentos INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
matricula INT NOT NULL,
data_treinamento DATE NOT NULL,
situacao_treinamento VARCHAR(20) NOT NULL,
aviso_treinamento VARCHAR(150),
CONSTRAINT fk_treinamento_funcionario
FOREIGN KEY (matricula)
REFERENCES funcionario(matricula)
ON DELETE CASCADE,
CONSTRAINT chk_situacao_treino
CHECK (situacao_treinamento IN ('Concluído', 'Pendente', 'Cancelado'))
);
